version: '3.3'

#
# The Firefly III Data Importer will ask you for the Firefly III URL and a "Client ID".
# You can generate the Client ID at http://localhost/profile (after registering)
# The Firefly III URL is: http://app:8080
#
# Other URL's will give 500 | Server Error
#

services:
  app:
    image: fireflyiii/core:latest
    hostname: app
    networks:
      - firefly
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - '80:8080'
    depends_on:
      - db
  db:
    image: mariadb
    hostname: fireflyiiidb
    networks:
      - firefly
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=secret_firefly_password
      - MYSQL_DATABASE=firefly
    volumes:
      - firefly_iii_db:/var/lib/mysql

  data_importer:
    image: fireflyiii/data-importer:latest
    hostname: data
    networks:
      - firefly
    restart: always
    ports:
      - '81:8080'
    depends_on:
      - app
    environment:
      - VANITY_URL=http://localhost
      - FIREFLY_III_URL=http://app:8080

volumes:
   firefly_iii_upload:
   firefly_iii_db:

networks:
  firefly:
    driver: bridge