# .github/workflows/ui-testing.yaml
name: Selenium UI Tests

on:
  pull_request:
    branches:
     - main    

jobs:
  selenium-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1  
        repository: tmeraslan/firefly-UI
        token: ${{ secrets.UI_TESTING_GITHUB_TOKEN }}  # Use the token to access the repo
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable wget unzip
        
    - name: Install ChromeDriver for Chrome 138
      run: |
        wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/138.0.7204.183/linux64/chromedriver-linux64.zip
        unzip chromedriver-linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Run Selenium tests
      env:
        CI: true
        HEADLESS: true
        FIREFLY_URL: 34.240.131.103:8080
      run: |
        pytest tests/ -v